### ISSUE TITLE
yash-syntax succeeds in parsing cmd string to List, but fails to parse it to Command or CompoundCommand

### ISSUE THREAD

**Issue by zjp-CN** [magicant/yash-rs#387]
```rust
let cmd = r#"cargo fmt; echo 1"#;
let ast: Command = cmd.parse().unwrap();
```

```
called `Result::unwrap()` on an `Err` value: Some(Error { 
  cause: Syntax(RedundantToken), 
  location: Location { code: Code { value: RefCell { value: "cargo fmt; echo 1" }, start_line_number: 1, source: Unknown }, range: 9..10 }
})
```

If it's parsed to CompoundCommand, then the error is ``called `Result::unwrap()` on an `Err` value: None``.

I thought the cmd string could be parsed as [CompoundCommand::Grouping](https://docs.rs/yash-syntax/0.10.0/yash_syntax/syntax/enum.CompoundCommand.html#variant.Grouping) variant to be CompoundCommand and Command.

**Comment by magicant** [comment]
To parse as a `Grouping`, you need to enclose the commands in braces:

```rust
let cmd = r#"{ cargo fmt; echo 1; }"#;
```

**Comment by zjp-CN** [comment]
Thanks! It works well.

Though I made a mistake after seeing your revised cmd string 🥲 

```rust
let cmd = r#"{cargo fmt; echo 1; }"#; // mistake on left brace without a whitespace
let ast: CompoundCommand = cmd.parse().unwrap(); // error: called `Result::unwrap()` on an `Err` value: None
```
